// This file contains ONLY the static data - safe to use in client components
export interface PostMeta {
  slug: string
  title: string
  date: string
  category: string
  categorySlug: string
  image: string
  readTime: string
  tags: string[]
  mdFile: string
  excerpt: string
}

// All 29 blog posts - static data only, no fs imports
export const allPosts: PostMeta[] = [
  // Revenue — Founders' Secrets
  {
    slug: 'turn-your-story-into-a-personal-brand-with-ai-agents-in-just-one-hour',
    title: 'Turn Your Story Into a Personal Brand with AI Agents in Just One Hour',
    date: '2025-08-01',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/Personal Brand AI Agents One Hour.jpg',
    readTime: '4 min read',
    tags: ['Personal Brand', 'AI Agents', 'Content Strategy'],
    mdFile: "Founders' Secrets/turn-your-story-into-a-personal-brand-with-ai-agents-in-just-one-hour/index",
    excerpt: "Your personal brand is the bridge that lets people see the person behind the success. With AI agents, founders can turn a single one-hour conversation into 90 authentic pieces of content.",
  },
  {
    slug: 'personal-brand-one-min-ai',
    title: 'Build a Personal Brand in 1 Minute a Day with AI',
    date: '2025-08-05',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/Personal Brand One Min AI.jpg',
    readTime: '5 min read',
    tags: ['Personal Brand', 'AI Agents', 'Thought Leadership'],
    mdFile: "Founders' Secrets/personal-brand-one-min-ai/index",
    excerpt: "Every founder has a story. With AI agents, building your personal brand can be effortless — authentic content crafted to reflect your vision, shared consistently without taking hours of your time.",
  },

  // Operations — Founders' Secrets
  {
    slug: 'the-ai-implementation-strategy-divide-why-smart-entrepreneurs-are-failing',
    title: 'The AI Implementation Strategy Divide: Why Smart Entrepreneurs Are Failing',
    date: '2025-09-15',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/AI Implementation Strategy Divide.png',
    readTime: '5 min read',
    tags: ['AI Implementation', 'Entrepreneurship', 'Strategy'],
    mdFile: "Founders' Secrets/the-ai-implementation-strategy-divide-why-smart-entrepreneurs-are-failing/index",
    excerpt: "The most technically skilled founders aren't the most successful with AI. Dave Hajdu's Hong Kong presentation revealed a fundamental divide that explains why most AI initiatives fail.",
  },

  // Innovation — Founders' Secrets
  {
    slug: 'ai-psychosis-mental-health-risk-ai-powered-future',
    title: 'AI Psychosis: Mental Health Risks in Our AI-Powered Future',
    date: '2025-10-01',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/AI Psychosis Mental Health.png',
    readTime: '8 min read',
    tags: ['AI in Business', 'Mental Health', 'Leadership'],
    mdFile: "Founders' Secrets/ai-psychosis-mental-health-risk-ai-powered-future/index",
    excerpt: "AI psychosis occurs when individuals develop psychological dependency on AI systems, losing critical thinking abilities — affecting approximately 23% of heavy AI users in business environments.",
  },
  {
    slug: 'understanding-ai-induced-psychosis-business-leaders',
    title: 'Understanding AI-Induced Psychosis for Business Leaders',
    date: '2025-10-08',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/Understanding AI Induced Psychosis.jpg',
    readTime: '6 min read',
    tags: ['AI in Business', 'Mental Health', 'Workforce'],
    mdFile: "Founders' Secrets/understanding-ai-induced-psychosis-business-leaders/index",
    excerpt: "AI-induced psychosis affects up to 3% of heavy AI users, causing delusions and reality distortion — and it's costing businesses an average of $47,000 per affected employee.",
  },
  {
    slug: 'georgetown-university-mba-students-ai-education-cultural-intelligence-2025',
    title: 'Georgetown University MBA Students: AI Education & Cultural Intelligence in 2025',
    date: '2025-11-01',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/Georgetown MBA AI Education.jpg',
    readTime: '6 min read',
    tags: ['AI Education', 'Cultural Intelligence', 'Leadership'],
    mdFile: "Founders' Secrets/georgetown-university-mba-students-ai-education-cultural-intelligence-2025/index",
    excerpt: "75% of Georgetown MBA students studying in Vietnam identified cultural intelligence gaps as their biggest challenge — revealing a critical disconnect in how business schools prepare leaders for AI-era global markets.",
  },

  // Revenue
  {
    slug: 'the-hospitality-data-gap-creating-truly-hotel-personalized-experiences',
    title: 'The Hospitality Data Gap: Creating Truly Hotel Personalized Experiences',
    date: '2025-07-05',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/The Hospitality Data Gap-1.jpeg',
    readTime: '5 min read',
    tags: ['Hospitality', 'Personalization'],
    mdFile: 'hospitality-data-gap-hotel-personalized-experiences',
    excerpt: 'Hotels collect massive amounts of data but rarely use it to create the personalized experiences guests expect. Here\'s how AI changes the equation.',
  },
  {
    slug: 'from-idea-to-interactive-blog-in-30-minutes-the-founders-automation-playbook',
    title: "From Idea to Interactive Blog in 30 Minutes: The Founder's Automation Playbook",
    date: '2025-11-01',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/From Idea to Interactive Blog in 30 Minutes.jpeg',
    readTime: '5 min read',
    tags: ['Automation', 'Content'],
    mdFile: 'from-idea-to-interactive-blog-in-30-minutes',
    excerpt: 'Learn how founders are using AI automation to go from a raw idea to a published, interactive blog post in under 30 minutes—without a content team.',
  },
  {
    slug: 'why-human-ai-collaboration-is-the-future-of-business-success',
    title: 'Why Human-AI Collaboration Is the Future of Business Success',
    date: '2025-06-10',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/Why Human-AI Collaboration.jpeg',
    readTime: '6 min read',
    tags: ['Human-AI', 'Collaboration'],
    mdFile: 'why-human-ai-collaboration-is-the-future-of-business-success',
    excerpt: 'The future of business success isn\'t human vs. AI — it\'s human and AI working together. Here\'s what that collaboration looks like in practice.',
  },
  {
    slug: 'how-ai-in-business-success-starts-with-strategic-symbolism',
    title: 'How AI in Business Success Starts with Strategic Symbolism',
    date: '2025-10-25',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/How AI in Business Success Starts with Strategic Symbolism.jpeg',
    readTime: '5 min read',
    tags: ['Vietnam', 'Business Strategy'],
    mdFile: 'how-ai-in-business-success-starts-with-strategic-symbolism',
    excerpt: 'The fastest path to AI adoption isn\'t technology — it\'s leadership. How symbolic action from the top creates the cultural shift that makes AI work.',
  },

  // Talent
  {
    slug: 'your-next-ai-hire-isnt-a-person',
    title: "Your Next AI Hire Isn't a Person",
    date: '2025-05-28',
    category: 'Talent',
    categorySlug: 'talent',
    image: '/blog/images/your next hire.jpeg',
    readTime: '5 min read',
    tags: ['AI Hiring', 'Business'],
    mdFile: 'your-next-ai-hire-isnt-a-person',
    excerpt: "Most companies don't fail at AI because of the tech. They fail because no one owns it. AI agents need managers, engineers, and real teams, just like people.",
  },
  {
    slug: 'why-ai-training-is-essential-for-your-career-success-in-the-digital-age',
    title: 'Why AI Training Is Essential for Your Career Success in the Digital Age',
    date: '2025-07-15',
    category: 'Talent',
    categorySlug: 'talent',
    image: '/blog/images/Why AI Training Is Essential.jpeg',
    readTime: '5 min read',
    tags: ['AI Training', 'Career'],
    mdFile: 'why-ai-training-is-essential-for-career-success',
    excerpt: 'AI literacy is the new competitive advantage. Leaders who invest in AI training today will be the ones setting strategy — and capturing the value — tomorrow.',
  },
  {
    slug: 'strategies-to-harness-top-performers-for-business-success',
    title: 'Strategies to Harness Top Performers for Business Success',
    date: '2025-09-12',
    category: 'Talent',
    categorySlug: 'talent',
    image: '/blog/images/Strategies to Harness Top Performers for Business Success.jpeg',
    readTime: '6 min read',
    tags: ['Performance', 'Vietnam'],
    mdFile: 'strategies-to-harness-top-performers-for-business-success',
    excerpt: 'High performers don\'t just produce more — they set the cultural standard. Here\'s how to identify, retain, and multiply your top performers using AI-powered systems.',
  },
  {
    slug: 'offshore-teams-remote-integration-with-ai',
    title: 'Offshore Teams Made Easy | Remote Integration with AI',
    date: '2025-07-10',
    category: 'Talent',
    categorySlug: 'talent',
    image: '/blog/images/Offshore Teams Made Easy.jpeg',
    readTime: '5 min read',
    tags: ['Offshore Teams', 'Remote Work'],
    mdFile: 'remote-team-offshore-integration',
    excerpt: 'Building a high-performing remote team in Vietnam doesn\'t have to be complicated. Here\'s the AI-driven approach that makes offshore integration seamless.',
  },
  {
    slug: 'how-one-decision-at-a-time-creates-high-performers-in-business-and-life',
    title: 'How One Decision at a Time Creates High Performers in Business and Life',
    date: '2025-08-18',
    category: 'Talent',
    categorySlug: 'talent',
    image: '/blog/images/How One Decision.jpeg',
    readTime: '5 min read',
    tags: ['Decision Making', 'High Performance'],
    mdFile: 'how-one-decision-at-a-time-creates-high-performers',
    excerpt: 'High performance isn\'t built through massive leaps — it\'s built one decision at a time. Learn the framework that turns daily choices into long-term excellence.',
  },
  {
    slug: 'strategies-to-harness-top-performers-hpc',
    title: 'Strategies to Harness Top Performers for Business Success',
    date: '2025-06-05',
    category: 'Talent',
    categorySlug: 'talent',
    image: '/blog/images/Strategies to Harness Top Performers.jpeg',
    readTime: '6 min read',
    tags: ['Performance', 'Culture'],
    mdFile: 'strategies-to-harness-top-performers-for-business-success',
    excerpt: 'Discover how AI-powered systems help you identify, develop, and retain the top performers who drive your culture and your business forward.',
  },

  // Operations
  {
    slug: '5-keys-to-reduce-ai-hallucinations-and-build-reliable-business-systems',
    title: '5 Keys to Reduce AI Hallucinations and Build Reliable Business Systems',
    date: '2025-10-15',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/5-Keys.jpg',
    readTime: '6 min read',
    tags: ['AI Reliability', 'Business Systems'],
    mdFile: '5-keys-to-reduce-ai-hallucinations',
    excerpt: 'AI hallucinations are the hidden flaw in today\'s most powerful systems. Here are five proven strategies to detect and reduce them before they spread.',
  },
  {
    slug: 'ai-data-strategy-why-data-moats-beat-model-wars-in-2025',
    title: 'AI Data Strategy: Why Data Moats Beat Model Wars in 2025',
    date: '2025-09-20',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/AI Data Strategy.jpeg',
    readTime: '7 min read',
    tags: ['Data Strategy', 'AI'],
    mdFile: 'ai-data-strategy-moats-beat-model-wars',
    excerpt: 'The real battle for AI dominance isn\'t happening at the model level — it\'s happening at the data level. Companies that build data moats will win.',
  },
  {
    slug: 'ai-in-data-migration-why-your-ai-program-is-really-a-data-problem',
    title: 'AI in Data Migration: Why Your AI Program Is Really a Data Problem',
    date: '2025-08-12',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/AI in Data Migration-1.jpeg',
    readTime: '6 min read',
    tags: ['Data Migration', 'AI Programs'],
    mdFile: 'ai-in-data-migration',
    excerpt: 'Before you can use AI effectively, you need your data in order. Why most AI programs are really data migration problems in disguise.',
  },
  {
    slug: 'why-ai-issues-are-really-data-problems-a-guide-for-future-ai-officers',
    title: 'Why AI Issues Are Really Data Problems: A Guide for Future AI Officers',
    date: '2025-06-18',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/Why AI Issues.jpeg',
    readTime: '6 min read',
    tags: ['AI Officers', 'Data'],
    mdFile: 'why-ai-issues-are-really-data-problems',
    excerpt: 'Every AI failure traces back to a data problem. Here\'s the guide future AI Officers need to diagnose and fix the root causes before they compound.',
  },
  {
    slug: 'ai-process-culture-performance-automation-that-works',
    title: 'AI for Performance Culture: Process Automation that Works',
    date: '2025-09-25',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/AI for Performance Culture-1.jpeg',
    readTime: '6 min read',
    tags: ['Culture', 'Process Automation'],
    mdFile: 'ai-process-culture-performance',
    excerpt: 'Process automation that actually works doesn\'t replace culture — it amplifies it. Here\'s how to build AI-powered processes your team will actually use.',
  },

  // Innovation
  {
    slug: '2026-ai-trends-5-game-changing-shifts-that-will-define-business-success',
    title: '2026 AI Trends: 5 Game-Changing Shifts That Will Define Business Success',
    date: '2025-11-10',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/2026 AI Trends.jpeg',
    readTime: '8 min read',
    tags: ['AI Trends', 'Business Strategy'],
    mdFile: '2026-ai-trends-5-game-changing-shifts',
    excerpt: 'The companies that will win in 2026 aren\'t the ones with the best AI tools — they\'re the ones with the best data. Five trends that will define the next year.',
  },
  {
    slug: 'business-research-assignment-that-could-transform-your-company-and-your-career',
    title: 'The Business Research Assignment That Could Transform Your Company (And Your Career)',
    date: '2025-09-30',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/The Business Research Assignment.jpeg',
    readTime: '6 min read',
    tags: ['Business Research', 'Leadership'],
    mdFile: 'business-research-assignment-transform-your-company',
    excerpt: 'One assignment that could change how you see your entire business — and your career trajectory. How structured AI-powered research unlocks real competitive intelligence.',
  },
  {
    slug: 'the-case-for-ai-co-ceos-and-ai-leadership-why-every-leader-needs-a-digital-decision-partner',
    title: 'The Case for AI Co-CEOs & AI Leadership: Why Every Leader Needs a Digital Decision Partner',
    date: '2025-08-20',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/The Case for AI Co-CEOs & AI Leadership.jpeg',
    readTime: '7 min read',
    tags: ['AI Leadership', 'Co-CEO'],
    mdFile: 'case-for-ai-co-ceo-ai-leadership',
    excerpt: 'Every leader needs a digital decision partner. Here\'s the case for treating AI not as a tool, but as a co-strategist integrated into your leadership team.',
  },
  {
    slug: 'why-smart-founders-are-already-planning-for-meta-ray-ban-glasses-even-when-demos-fail',
    title: 'Why Smart Founders Are Already Planning for Meta Ray-Ban Glasses (Even When Demos Fail)',
    date: '2025-05-20',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/Why Smart Founders.jpeg',
    readTime: '5 min read',
    tags: ['AR Glasses', 'Meta'],
    mdFile: 'why-smart-founders-are-planning-for-meta-ray-ban-glasses',
    excerpt: 'Technology always catches up. The founders building for Meta Ray-Ban today will have a massive first-mover advantage when the hardware finally delivers.',
  },
  {
    slug: 'tech-in-entrepreneurship-how-ai-is-disrupting-the-role-of-the-founder',
    title: 'Tech In Entrepreneurship: How AI is disrupting the role of the Founder',
    date: '2025-08-05',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/Tech In Entrepreneurship.jpeg',
    readTime: '6 min read',
    tags: ['Entrepreneurship', 'Vietnam'],
    mdFile: 'tech-in-entrepreneurship-how-ai-is-disrupting-the-role-of-the-founder',
    excerpt: 'AI isn\'t just changing how businesses operate — it\'s fundamentally disrupting what it means to be a founder. Here\'s what the new entrepreneur looks like.',
  },
  {
    slug: 'vietnam-ai-silicon-valley-of-southeast-asia',
    title: 'Vietnam and the Rise of AI — The New Silicon Valley of Southeast Asia',
    date: '2025-07-22',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/Vietnam and the Rise of AI.jpeg',
    readTime: '7 min read',
    tags: ['Vietnam', 'AI Rise'],
    mdFile: 'vietnam-ai-silicon-valley',
    excerpt: 'Vietnam is emerging as Southeast Asia\'s most exciting AI hub. Why the country\'s talent, culture, and government investment make it the region\'s next Silicon Valley.',
  },
  {
    slug: 'vietnam-ai-business-law-what-leaders-should-know',
    title: "Vietnam's AI Rules — What Leaders Should Know",
    date: '2025-06-28',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: "/blog/images/Vietnams-AI-Rules.jpeg",
    readTime: '5 min read',
    tags: ['Vietnam', 'AI Regulation'],
    mdFile: 'vietnam-ai-business-law',
    excerpt: 'Vietnam\'s government is moving fast on AI regulation. What business leaders operating in — or entering — the Vietnamese market need to know right now.',
  },
  {
    slug: 'ai-strategies-for-a-high-performing-culture',
    title: '5 AI Strategies for a High-Performing Culture',
    date: '2025-11-05',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/5 AI Strategies.jpeg',
    readTime: '6 min read',
    tags: ['Culture', 'AI Strategy'],
    mdFile: 'ai-strategies-high-performing-culture',
    excerpt: 'Culture doesn\'t change because you buy an AI tool — it changes when leaders model the behavior. Five AI strategies that build high-performing cultures from the inside out.',
  },

  // Revenue — AI in Business
  {
    slug: 'ai-driven-content-strategy-vespa',
    title: 'AI-Driven Content Strategy Boosts Tourism Performance',
    date: '2025-04-01',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/ai-driven-content-strategy-vespa.jpeg',
    readTime: '5 min read',
    tags: ['Content Strategy', 'AI Marketing', 'Tourism'],
    mdFile: 'AI in Business/ai-driven-content-strategy-vespa/index',
    excerpt: "A mid-market tourism enterprise achieved 30% revenue growth and 156% increase in organic search traffic in 12 months through AI-driven content and analytics strategy. Here's the implementation blueprint.",
  },
  {
    slug: 'ai-personalization-flywheel-transforming-hospitality-revenue',
    title: 'AI Personalization Flywheel: Transforming Hospitality Revenue',
    date: '2025-06-15',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/ai-personalization-flywheel-transforming-hospitality-revenue.jpg',
    readTime: '6 min read',
    tags: ['Hospitality', 'AI Personalization', 'Revenue'],
    mdFile: 'AI in Business/ai-personalization-flywheel-transforming-hospitality-revenue/index',
    excerpt: "71% of travelers expect personalized experiences, yet only 20% of hotels have implemented AI personalization despite proven revenue gains of up to 30%. The AI Personalization Flywheel changes everything.",
  },
  {
    slug: 'ai-salesforce-in-action',
    title: 'Four Ways an AI Salesforce Makes Your Sales Process Way Better',
    date: '2025-07-15',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/ai-salesforce-in-action.jpeg',
    readTime: '5 min read',
    tags: ['AI Sales', 'Salesforce', 'CRM'],
    mdFile: 'AI in Business/ai-salesforce-in-action/index',
    excerpt: "We've been implementing AI within sales systems for a while now, and we've seen it create massive improvements in four key areas. Here's how an AI Salesforce with a human in the loop transforms revenue generation.",
  },
  {
    slug: 'ai-tiktok-marketing-vietnam',
    title: 'AI-Powered TikTok Marketing for Vietnamese Businesses',
    date: '2025-09-01',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/ai-tiktok-marketing-vietnam.png',
    readTime: '5 min read',
    tags: ['TikTok', 'Vietnam', 'AI Marketing'],
    mdFile: 'AI in Business/ai-tiktok-marketing-vietnam/index',
    excerpt: "For businesses in Vietnam, AI-driven TikTok marketing isn't just a trend — it's a necessity. AI agents help brands stay ahead of competition, increase engagement and conversions, and scale marketing efforts effortlessly.",
  },
  {
    slug: 'boost-your-business-with-an-ai-driven-landing-page-strategy',
    title: 'Boost Your Business with an AI-Driven Landing Page Strategy',
    date: '2025-10-15',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/boost-your-business-with-an-ai-driven-landing-page-strategy.png',
    readTime: '5 min read',
    tags: ['Landing Pages', 'AI Marketing', 'Conversion Optimization'],
    mdFile: 'AI in Business/boost-your-business-with-an-ai-driven-landing-page-strategy/index',
    excerpt: "A client interview transcript does more than convey facts — it brings authenticity and emotional resonance. AI agents can transform your client conversations into compelling landing pages that convert, in a fraction of the time.",
  },
  {
    slug: 'enhancing-sales-coaching-with-ai-a-nepq-framework-approach',
    title: 'Enhancing Sales Coaching with AI: A NEPQ Framework Approach',
    date: '2025-02-01',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/enhancing-sales-coaching-with-ai-a-nepq-framework-approach.jpg',
    readTime: '5 min read',
    tags: ['Sales Coaching', 'NEPQ', 'AI Sales'],
    mdFile: 'AI in Business/enhancing-sales-coaching-with-ai-a-nepq-framework-approach/index',
    excerpt: "Imagine your team having a 24-hour AI Sales Coach for every meeting. The NEPQ (Neuro-Emotional Persuasion Questioning) framework combined with AI analysis creates a sales coaching capability that was previously available only to the largest organizations.",
  },
  {
    slug: 'marketing-everywhere-campaign-in-30-minutes',
    title: 'Marketing Everywhere: Launch a Full Campaign in 30 Minutes with AI',
    date: '2025-05-10',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/marketing-everywhere-campaign-in-30-minutes.webp',
    readTime: '5 min read',
    tags: ['Marketing Automation', 'Content Strategy', 'Multi-Channel Marketing'],
    mdFile: 'AI in Business/marketing-everywhere-campaign-in-30-minutes/index',
    excerpt: "The Marketing Everywhere approach uses AI agents to transform a single core idea into a complete multi-channel campaign — blog post, social content, email, and video script — in 30 minutes. Here's the exact system.",
  },
  {
    slug: 'master-personal-branding-in-2025-with-ai-agents-and-geo',
    title: 'Master Personal Branding in 2025 with AI Agents and GEO',
    date: '2025-06-10',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/master-personal-branding-in-2025-with-ai-agents-and-geo.png',
    readTime: '6 min read',
    tags: ['Personal Branding', 'GEO', 'AI Agents'],
    mdFile: 'AI in Business/master-personal-branding-in-2025-with-ai-agents-and-geo/index',
    excerpt: "Personal branding has evolved from a marketing trend to a business necessity. With digital landscapes becoming increasingly competitive, business leaders must leverage both traditional SEO and emerging Generative Engine Optimization (GEO) strategies to build authentic personal brands.",
  },
  {
    slug: 'video-3-0-ai-powered-video-communication-for-executives',
    title: 'Why AI Video 3.0 Is the New Language of Leadership',
    date: '2025-10-10',
    category: 'Revenue',
    categorySlug: 'revenue',
    image: '/blog/images/video-3-0-ai-powered-video-communication-for-executives.jpg',
    readTime: '5 min read',
    tags: ['Video', 'AI Agents', 'Leadership'],
    mdFile: 'AI in Business/video-3-0-ai-powered-video-communication-for-executives/index',
    excerpt: "Executive video production used to mean hours in a studio. Video 3.0 — the integration of AI into every step of the video content lifecycle — changes everything. Here's how modern leaders scale thought leadership without burnout.",
  },

  // Talent — AI in Business
  {
    slug: 'ai-in-remote-hybrid-marketing-teams',
    title: 'How AI Agents Are Powering Remote & Hybrid Marketing Teams',
    date: '2025-05-01',
    category: 'Talent',
    categorySlug: 'talent',
    image: '/blog/images/ai-in-remote-hybrid-marketing-teams.jpeg',
    readTime: '5 min read',
    tags: ['Remote Work', 'AI Agents', 'Marketing Teams'],
    mdFile: 'AI in Business/ai-in-remote-hybrid-marketing-teams/index',
    excerpt: "The shift to remote and hybrid work has fundamentally changed how marketing teams operate. AI Agents have emerged as the ultimate co-pilots for remote marketing teams — optimizing workflows, automating decision-making, and streamlining creative processes.",
  },
  {
    slug: 'ai-role-teacher-readiness',
    title: "Teacher Readiness: AI's Role in Education's Future",
    date: '2025-07-01',
    category: 'Talent',
    categorySlug: 'talent',
    image: '/blog/images/ai-role-teacher-readiness.jpeg',
    readTime: '5 min read',
    tags: ['AI Education', 'Teacher Training', 'EdTech'],
    mdFile: 'AI in Business/ai-role-teacher-readiness/index',
    excerpt: "Imagine a world where students no longer need teachers and are capable of teaching themselves with AI. This isn't a distant sci-fi scenario — it's a potential reality if educators can't keep pace with their increasingly AI-savvy students.",
  },

  // Operations — AI in Business
  {
    slug: 'ai-agent-meetings-quiz',
    title: 'Is Your Team Ready for AI Agent Meetings? Take the Quiz',
    date: '2025-03-01',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/ai-agent-meetings-quiz.jpg',
    readTime: '5 min read',
    tags: ['AI Meetings', 'AI Agents', 'Productivity'],
    mdFile: 'AI in Business/ai-agent-meetings-quiz/index',
    excerpt: "AI agents are transforming how meetings work — from automated note-taking and action item extraction to pre-meeting research and post-meeting follow-up. Find out if your team is ready to unlock these productivity gains.",
  },
  {
    slug: 'ai-agents-content-seo-shift',
    title: 'AI Agents and the Content SEO Shift: What Changes Now',
    date: '2025-03-15',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/ai-agents-content-seo-shift.jpg',
    readTime: '5 min read',
    tags: ['SEO', 'AI Agents', 'Content Strategy'],
    mdFile: 'AI in Business/ai-agents-content-seo-shift/index',
    excerpt: "Google's Search Generative Experience and AI-driven search models are shifting SEO away from traditional blue links toward AI-generated summaries. This isn't incremental change — it's a structural shift in how organic traffic works.",
  },
  {
    slug: 'ai-focus-group-research-book-title',
    title: 'How AI Focus Group Research Uncovered the Perfect Book Title',
    date: '2025-04-15',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/ai-focus-group-research-book-title.jpeg',
    readTime: '5 min read',
    tags: ['AI Research', 'Focus Group', 'Market Research'],
    mdFile: 'AI in Business/ai-focus-group-research-book-title/index',
    excerpt: "Finding the perfect title for a book can significantly impact its market success. We used AI to simulate focus group research from 20 participants across diverse countries — yielding valuable insights in a fraction of the time and cost of traditional methods.",
  },
  {
    slug: 'ai-market-research-strategy',
    title: 'AI-Powered Market Research: Smarter Strategy Starts Here',
    date: '2025-06-01',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/ai-market-research-strategy.png',
    readTime: '5 min read',
    tags: ['Market Research', 'AI Strategy', 'Business Intelligence'],
    mdFile: 'AI in Business/ai-market-research-strategy/index',
    excerpt: "Market research has traditionally been a bottleneck for businesses — expensive, time-consuming, and sometimes misleading. AI technology is fundamentally changing this paradigm, offering faster, more cost-effective, and potentially more accurate insights.",
  },
  {
    slug: 'ai-search-optimization-google-traffic-revolution',
    title: "AI Search Optimization: Adapting to Google's Traffic Revolution",
    date: '2025-08-01',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/ai-search-optimization-google-traffic-revolution.webp',
    readTime: '6 min read',
    tags: ['SEO', 'Google', 'AI Search'],
    mdFile: 'AI in Business/ai-search-optimization-google-traffic-revolution/index',
    excerpt: "The New York Times saw its organic search traffic share drop from 44% to 36.5% in just three years. This isn't just a media problem — it's a wake-up call for every business depending on search visibility for lead generation.",
  },
  {
    slug: 'ai-social-media-shift',
    title: "The AI Social Media Shift: What's Changing and How to Win",
    date: '2025-08-15',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/ai-social-media-shift.jpeg',
    readTime: '5 min read',
    tags: ['Social Media', 'AI Marketing', 'Content Strategy'],
    mdFile: 'AI in Business/ai-social-media-shift/index',
    excerpt: "AI is reshaping social media from the ground up — how content is created, distributed, discovered, and measured. The brands that win will use AI as a strategic tool, not a crutch, while keeping storytelling personal.",
  },
  {
    slug: 'crm-alternatives-data-control',
    title: 'CRM Alternatives: Why Data Control Is Your Real Competitive Advantage',
    date: '2025-11-15',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/crm-alternatives-data-control.jpeg',
    readTime: '5 min read',
    tags: ['CRM', 'Data Strategy', 'Customer Data'],
    mdFile: 'AI in Business/crm-alternatives-data-control/index',
    excerpt: "The most sophisticated CRM tools still rent you someone else's infrastructure. Organizations that own their data layer unlock personalization capabilities that rental systems simply cannot match — and competitive advantages that compound over time.",
  },
  {
    slug: 'gpt-41-changes-everything-ai-prompting',
    title: 'GPT-4.1 Changes Everything About AI Prompting',
    date: '2025-02-15',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/gpt-41-changes-everything-ai-prompting.jpeg',
    readTime: '5 min read',
    tags: ['GPT-4.1', 'AI Prompting', 'Prompt Engineering'],
    mdFile: 'AI in Business/gpt-41-changes-everything-ai-prompting/index',
    excerpt: "Everyone's treating AI prompting like magic spells, but GPT-4.1 demands we think like architects. The latest OpenAI guide reveals a fundamental shift: from linguistic creativity to instruction architecture.",
  },
  {
    slug: 'harness-ai-agent-for-optimized-seo-blog-articles',
    title: 'Harness AI Agent for Optimized SEO Blog Articles',
    date: '2025-01-15',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/harness-ai-agent-for-optimized-seo-blog-articles.jpeg',
    readTime: '5 min read',
    tags: ['SEO', 'AI Agents', 'Content Marketing'],
    mdFile: 'AI in Business/harness-ai-agent-for-optimized-seo-blog-articles/index',
    excerpt: "If you've ever spent countless hours manually tweaking blog posts for better rankings, AI Agents are changing the game. These intelligent tools automate and optimize every stage of the content creation process — so your team focuses on strategy, not busy work.",
  },
  {
    slug: 'how-ai-search-optimization-is-changing-business-teams',
    title: 'How AI Search Optimization Is Changing Business Teams',
    date: '2025-01-01',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/how-ai-search-optimization-is-changing-business-teams.jpg',
    readTime: '6 min read',
    tags: ['SEO', 'Marketing', 'Content Strategy'],
    mdFile: 'AI in Business/how-ai-search-optimization-is-changing-business-teams/index',
    excerpt: "65% of Google searches now end without a click to any website — quietly devastating traditional marketing strategies. The solution: mobilizing your entire team as strategic content amplifiers.",
  },
  {
    slug: 'how-to-create-typeform-surveys-with-ai',
    title: 'How to Create Typeform Surveys with AI',
    date: '2025-01-30',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/how-to-create-typeform-surveys-with-ai.jpeg',
    readTime: '4 min read',
    tags: ['Typeform', 'AI Tools', 'Survey Design'],
    mdFile: 'AI in Business/how-to-create-typeform-surveys-with-ai/index',
    excerpt: "Want to create Typeform surveys with AI in minutes instead of hours? Here's exactly how to leverage Claude AI to transform a lengthy document into a sleek, user-friendly Typeform survey — complete with workarounds for platform limitations.",
  },
  {
    slug: 'how-to-transform-chatgpt-ai-conversations-into-powerful-ideas',
    title: 'How To Transform ChatGPT AI Conversations Into Powerful Ideas',
    date: '2025-02-10',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/how-to-transform-chatgpt-ai-conversations-into-powerful-ideas.jpeg',
    readTime: '5 min read',
    tags: ['ChatGPT', 'Content Marketing', 'AI Conversations'],
    mdFile: 'AI in Business/how-to-transform-chatgpt-ai-conversations-into-powerful-ideas/index',
    excerpt: "Forward-thinking marketers are discovering that ChatGPT AI conversations can be goldmines of authentic, ready-to-use content. Here's how to systematically capture and repurpose these conversations into marketing assets across every channel.",
  },
  {
    slug: 'how-to-use-ai-tools-for-research-to-achieve-better-results',
    title: 'How to Use AI Tools for Research to Achieve Better Results',
    date: '2025-02-20',
    category: 'Operations',
    categorySlug: 'operations',
    image: '/blog/images/how-to-use-ai-tools-for-research-to-achieve-better-results.jpg',
    readTime: '5 min read',
    tags: ['AI Research', 'AI Tools', 'Productivity'],
    mdFile: 'AI in Business/how-to-use-ai-tools-for-research-to-achieve-better-results/index',
    excerpt: "AI research tools are dramatically changing what's possible for individuals and teams doing knowledge work. Here's a practical framework for integrating AI into your research process to get faster, more comprehensive, and more reliable results.",
  },

  // Innovation — AI in Business
  {
    slug: 'ai-legacy-building',
    title: 'AI-Enhanced Legacy Building: Transforming Expertise into Lasting Impact',
    date: '2025-05-15',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/ai-legacy-building.png',
    readTime: '5 min read',
    tags: ['AI Legacy', 'Personal Brand', 'Knowledge Management'],
    mdFile: 'AI in Business/ai-legacy-building/index',
    excerpt: "Legacy businesses represent the highest expression of professional accomplishment. Today's AI can transform decades of accumulated expertise into scalable assets — books, frameworks, training programs — that continue providing value long after you've moved on.",
  },
  {
    slug: 'amazon-claude-ai-dominance-strategy',
    title: "How Amazon's $4B Investment Powers Claude AI Dominance",
    date: '2025-09-15',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/amazon-claude-ai-dominance-strategy.jpeg',
    readTime: '5 min read',
    tags: ['Amazon', 'Claude', 'AI Strategy'],
    mdFile: 'AI in Business/amazon-claude-ai-dominance-strategy/index',
    excerpt: "When Amazon invested $4 billion in Anthropic, most analysts focused on the funding amount. They missed the real story: Amazon secured access to the most comprehensive dataset for building domain-specific AI supremacy across coding, writing, and commerce.",
  },
  {
    slug: 'apple-intelligence-intimate-personal-ai-strategy',
    title: 'How Apple Intelligence Shapes Personal AI Strategy',
    date: '2025-10-01',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/apple-intelligence-intimate-personal-ai-strategy.jpeg',
    readTime: '5 min read',
    tags: ['Apple', 'AI Strategy', 'Data Privacy'],
    mdFile: 'AI in Business/apple-intelligence-intimate-personal-ai-strategy/index',
    excerpt: "While competitors race to accumulate massive datasets in the cloud, Apple has chosen a fundamentally different path — processing intimate personal data on-device, creating unprecedented understanding of individual users while maintaining absolute privacy.",
  },
  {
    slug: 'chatgpt-billion-user-advantage-general-ai-dominance',
    title: "How ChatGPT Leverages Microsoft's Workplace Data for AI Dominance",
    date: '2025-11-01',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/chatgpt-billion-user-advantage-general-ai-dominance.jpg',
    readTime: '5 min read',
    tags: ['ChatGPT', 'Microsoft', 'AI Strategy'],
    mdFile: 'AI in Business/chatgpt-billion-user-advantage-general-ai-dominance/index',
    excerpt: "ChatGPT has quietly solved the most challenging problem in AI: understanding what humans actually want across every use case. Through Microsoft's workplace data and feedback from over a billion users, it's built the most comprehensive dataset of human preferences ever assembled.",
  },
  {
    slug: 'elon-musk-twitter-data-strategy-ai-play',
    title: "Elon Musk's Twitter Data Strategy: AI Lessons for Leaders",
    date: '2025-12-01',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/elon-musk-twitter-data-strategy-ai-play.jpeg',
    readTime: '5 min read',
    tags: ['AI Strategy', 'Data Strategy', 'Elon Musk'],
    mdFile: 'AI in Business/elon-musk-twitter-data-strategy-ai-play/index',
    excerpt: "Critics never saw the real strategy: Musk didn't buy a social platform. He bought the world's largest, human-curated index of the web — a living signal layer that traditional crawlers like Google can't replicate.",
  },
  {
    slug: 'human-insight-ai-agents-business-landscape',
    title: 'Human Insight Remains Vital in the Expanding AI Agent Landscape',
    date: '2025-03-10',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/human-insight-ai-agents-business-landscape.jpeg',
    readTime: '5 min read',
    tags: ['AI Agents', 'Human Intelligence', 'AI Strategy'],
    mdFile: 'AI in Business/human-insight-ai-agents-business-landscape/index',
    excerpt: "AI agents are revolutionizing how businesses operate, automate processes, and make decisions. Yet as these capabilities expand, a crucial question emerges: what role should human insight play in an increasingly automated business environment?",
  },
  {
    slug: 'leadership-ai-transformation-foundation',
    title: 'Leadership Is the Foundation for Successful AI Transformation',
    date: '2025-04-10',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/leadership-ai-transformation-foundation.jpg',
    readTime: '5 min read',
    tags: ['AI Leadership', 'AI Transformation', 'Change Management'],
    mdFile: 'AI in Business/leadership-ai-transformation-foundation/index',
    excerpt: "In the rush to implement AI solutions, organizations often bypass the critical foundation: leadership. This oversight isn't just problematic — it's the primary reason many AI initiatives fail to deliver on their promises.",
  },
  {
    slug: 'offline-ai-real-time-enterprise-edge',
    title: 'Offline AI: Real-Time Power for Future-Ready Enterprises',
    date: '2025-07-10',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/offline-ai-real-time-enterprise-edge.png',
    readTime: '5 min read',
    tags: ['Offline AI', 'Edge AI', 'Enterprise'],
    mdFile: 'AI in Business/offline-ai-real-time-enterprise-edge/index',
    excerpt: "Google's AI Edge Gallery lets users run AI models entirely on their devices — no cloud, no data sharing, no internet required. What started as a consumer breakthrough has profound implications for enterprise strategy.",
  },
  {
    slug: 'open-weight-ai-models-enterprise-data-security-2025',
    title: 'Open-Weight AI Models & Enterprise Data Security in 2025',
    date: '2025-08-10',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/open-weight-ai-models-enterprise-data-security-2025.jpg',
    readTime: '5 min read',
    tags: ['Open Source AI', 'Enterprise Security', 'Data Privacy'],
    mdFile: 'AI in Business/open-weight-ai-models-enterprise-data-security-2025/index',
    excerpt: "90% of enterprise AI implementations send sensitive data to external servers, creating compliance risks and ongoing costs. OpenAI's open-weight models eliminate these risks by running entirely on local infrastructure.",
  },
  {
    slug: 'veo-3-video-generation-empire-youtube-data-advantage',
    title: "Google's Video AI Dominance: Why VEO 3 Will Rule Visual Content",
    date: '2025-09-10',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/veo-3-video-generation-empire-youtube-data-advantage.png',
    readTime: '5 min read',
    tags: ['Google', 'VEO 3', 'Video AI'],
    mdFile: 'AI in Business/veo-3-video-generation-empire-youtube-data-advantage/index',
    excerpt: "The battle for video generation supremacy was decided years ago on YouTube. Google's VEO 3 isn't just another AI model — it's the inevitable result of owning humanity's largest archive of creative expression.",
  },
  {
    slug: 'why-chat-gpt-5-matters-in-age-of-incremental-ai-progress',
    title: 'Why ChatGPT-5 Matters in an Age of Incremental AI Progress',
    date: '2025-11-10',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/why-chat-gpt-5-matters-in-age-of-incremental-ai-progress.jpg',
    readTime: '5 min read',
    tags: ['AI Models', 'ChatGPT', 'Business Strategy'],
    mdFile: 'AI in Business/why-chat-gpt-5-matters-in-age-of-incremental-ai-progress/index',
    excerpt: "ChatGPT-5 was called a 'flop' by some. But this misses the real story: we've entered an era where progress in foundational AI is becoming more incremental — and the implications for business strategy are profound.",
  },
  {
    slug: 'why-every-business-needs-a-chief-ai-officer-leadership-trumps-technology',
    title: 'Why Every Business Needs a Chief AI Officer Today',
    date: '2025-12-01',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/why-every-business-needs-a-chief-ai-officer-leadership-trumps-technology.jpg',
    readTime: '5 min read',
    tags: ['Chief AI Officer', 'AI Leadership', 'AI Strategy'],
    mdFile: 'AI in Business/why-every-business-needs-a-chief-ai-officer-leadership-trumps-technology/index',
    excerpt: "Most companies today operate in deeply entrenched silos — and AI makes this problem worse before it makes it better. The solution: a Chief AI Officer who doesn't just oversee technology, but architects the entire AI transformation strategy.",
  },
  {
    slug: 'why-grok-4-s-success-proves-strategic-ai-planning-beats-first-mover-advantage',
    title: "Why Grok 4's Success Proves Strategic AI Planning Beats First-Mover Advantage",
    date: '2025-12-15',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/why-grok-4-s-success-proves-strategic-ai-planning-beats-first-mover-advantage.webp',
    readTime: '5 min read',
    tags: ['AI Strategy', 'Grok', 'Business Strategy'],
    mdFile: 'AI in Business/why-grok-4-s-success-proves-strategic-ai-planning-beats-first-mover-advantage/index',
    excerpt: "While ChatGPT dominated headlines for nearly a decade, Elon Musk quietly orchestrated a masterclass in long-term strategic thinking. Grok 4's breakthrough validates a fundamental principle: strategic patience beats early market entry.",
  },
  {
    slug: 'ai-program-vs-ai-tool',
    title: 'AI Program vs AI Tool: I Built a Real One, and the Number Stung',
    date: '2026-06-28',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/ai-program-vs-ai-tool.webp',
    readTime: '5 min read',
    tags: ['AI Program', 'AI Strategy', 'AI Consulting'],
    mdFile: 'AI in Business/ai-program-vs-ai-tool/index',
    excerpt: "Most companies buy AI tools when they need an AI program built on their own data. I built one on myself in a day, and it told me the truth about how I lead. Here is the difference, and why it is the whole game.",
  },
  {
    slug: 'the-other-50-percent-of-leadership',
    title: 'The Other 50% of Leadership',
    date: '2026-06-29',
    category: 'Innovation',
    categorySlug: 'innovation',
    image: '/blog/images/the-other-50-percent-of-leadership.webp',
    readTime: '9 min read',
    tags: ['AI Leadership', 'AI Strategy', 'Infinite Leverage'],
    mdFile: 'AI in Business/the-other-50-percent-of-leadership/index',
    excerpt: "AI-era leadership now needs a second skill set: workflow design, information architecture, and writing instructions for AI. Here is how to build it.",
  },
]

export const categories = [
  { slug: 'revenue',    label: 'Revenue' },
  { slug: 'talent',     label: 'Talent' },
  { slug: 'operations', label: 'Operations' },
  { slug: 'innovation', label: 'Innovation' },
  { slug: 'claude',     label: 'Claude' },
]
